### ISSUE TITLE
"None" slider option which acts as toggle?

### ISSUE THREAD

**Issue by KairuByte** [mattieha/slider-button-card#12]
I would very much appreciate if there was a "none" option for the slider setting, and tapping the card on the "slider" area would simply act as a toggle. As things are, entities with only an on/off state are quite frustrating to use.

This would also allow for switching between toggle and slider states with other cards, without losing out on the look or the need to replicate the look through a different card.

**Comment by mattieha** [comment]
I like the idea, and shouldn't be to hard to implement.
Just for my curiosity, what part do you find frustrating? Since there is already a toggle in the right upper corner beside the "slide" feature.

**Comment by KairuByte** [comment]
I've been building a dashboard using a laptop, with only the trackpad for mouse input. I keep trying to tap the button, my brain expecting the state to change, but it doesn't unless I drag.

The toggle in the top right is a little harder to hit using something as clumsy as a trackpad.

**Comment by mattieha** [comment]
@KairuByte this is now released in [v1.2.0](https://github.com/mattieha/slider-button-card/releases/tag/v1.2.0)

Option added: slider.toggle_on_click which defaults to false.
When set to true it forces the slider to act as a toggle, sliding will be disabled.

For now you will have to add it manually in the yaml, UI editor option will follow soon.

Please let me know if this works for you.

**Comment by KairuByte** [comment]
Thank you very much, I actually saw the update and converted all applicable cards. This works absolutely perfectly!
