### ISSUE TITLE
Reverse the open/down cursor

### ISSUE THREAD

**Issue by S1M8N** [mattieha/slider-button-card#15]
Hello,

First of all thank you for this wonderful Frontend!

I noticed that with cover mode, when we take the cursor and pull it down, it opens the shutter. I was wondering if it was possible to add a reverse option. Put the cursor up to raise the shutter and put the cursor down to lower the shutter?

https://i.imgur.com/tTDBfOD.png
https://i.imgur.com/Q4tAlFw.png

I don't know if it's clear but don't hesitate to let me know.

thank you for everything

Simon

**Comment by wielkim** [comment]
I have exacly the same problem. Kindly ask, for invert option.

**Comment by alexisteleco** [comment]
First and foremost, thanks for this custom component, I searched for a cover component and was not satisfied until I found this one. Nice work.

On the other hand, I have the same problem described above. An invert option would be a perfect solution for me.

**Comment by yaronbl** [comment]
One more vote for this. I'm using Shelly2.5 for my covers. They report 100% for open, and 0% for closed - meaning the cover is now covering the entire windows. A invert option will be great!

**Comment by mattieha** [comment]
Thanks for the feedback! 
At the moment I'm using a Cover Template to simulate a cover entity, because I don't own a smart cover (yet).
I've added it to the roadmap, will definitely implement this.

**Comment by Nornode** [comment]
Yeah, Awsome! 
Indeed, I had the same trouble finding a small, efficient yet beautiful, and customizable card for my covers.
The logic in this card seems to be reversed to me, pulling down will _open_ covers, when in fact, when pulling down would close the covers in the room. I'm sure there are tricks that can be made in HA on this, but, it would complicate other things I guess.
Another and related way to make it more intuitive would be to be able to customize the Open/Close clour. Having the clour you "pull-down" darker, and the one "behind" the cover lighter.


If it matters: I'm using Zigbee2Mqtt and IKEA Fyrtur

Again, many many thanks for a great and very appreciative new card.

**Comment by Mearman** [comment]
looking forward to this merging in. my partner keeps forgetting it's reversed

**Comment by mattieha** [comment]
This is now implemented in v1.4.0, please let me know if this works for you guys.

**Comment by yaronbl** [comment]
Just updated. Working great! Thanks for fixing this so quick!

**Comment by faquaresma** [comment]
Hi, 

How can i configure reverse ? I did not find. 

Thanks

**Comment by mattieha** [comment]
@faquaresma This is now the default behaviour, no need to change anything.

**Comment by Mearman** [comment]
@mattieha would it be possible to add a way to optionally/manually invert it? I can't think of a specific example, but I can imagine it being useful for some users.

**Comment by mattieha** [comment]
@Mearman Yes I thought about that and will add it in the future. Although for the cover domain I think this should just be the default behaviour without the need to manually reverse it.
When I made the card I misunderstood how the cover & percentage exactly works, because I don't own a smart cover (yet).

**Comment by red-machine95** [comment]
> 
> 
> This is now implemented in v1.4.0, please let me know if this works for you guys.

After updating and clearing the cache, reverse position does not work!
I use a Shelly 2.5 for the blinds and for me it's 100% at the top and not at the bottom as it continues to happen...

**Comment by mkjustuk** [comment]
> @Mearman Yes I thought about that and will add it in the future. Although for the cover domain I think this should just be the default behaviour without the need to manually reverse it.
> When I made the card I misunderstood how the cover & percentage exactly works, because I don't own a smart cover (yet).

Yes please, this card is great for awnings (patio shades etc) in the triangle version, but with the original 'backwards' logic to open as you drag out the triangle, to look like the shade rolling out over the patio etc).

**Comment by mattieha** [comment]
@mkjustuk Good point, that's a valid use case. My apologies for having the default reverse logic as implemented now doesn't work for you. I'm still trying to figure out all the different ways the cover entities are working.

**Comment by mkjustuk** [comment]
> @mkjustuk Good point, that's a valid use case. My apologies for having the default reverse logic as implemented now doesn't work for you. I'm still trying to figure out all the different ways the cover entities are working.
> 
> I'll try to add the reverse option this weekend.

Thank you, that will be great and appreciated so much. The card is so good, I'm using it for lots of things already. Don't worry about the default being that way for now, I rolled back to an earlier version until then.

**Comment by mattieha** [comment]
@Mearman @mkjustuk 
In v.1.7.0 there is a `slider.invert` option, for cover entities it defaults to `true`.
Add `invert: false` in yaml to invert the logic, no visual editor option yet.
Please let me know if this works for you.

**Comment by mkjustuk** [comment]
Thank you! Working perfectly for me now for my awnings on 1.7.0
