### ISSUE TITLE
compact mode with action in custom mode

### ISSUE THREAD

**Issue by maximatchev** [mattieha/slider-button-card#157]
**Checklist:**

- [x] I updated to the latest version available
- [x] I cleared the cache of my browser

**Release with the issue:**
08 Jul 2021  v1.10.3 
**Last working release (if known):**
08 Jul 2021  v1.10.3 
**Browser and Operating System:**
Chrome 97.0.4692.71

**Description of problem:**

```
...
compact: true
action_button:
  mode: custom
...
```
icon is in the second row below the name of entity

**Javascript errors shown in the web inspector (if applicable):**

```

```

**Additional information:**

**Comment by jscongdon** [comment]
add `show: true` as a sub of `action_button`
```
compact: true
action_button:
  mode: custom
  show: true
```
If you use the Visual Editor when adding the card all the default settings will be set and you will not have this issue. Use my solution above otherwise.

**Comment by maximatchev** [comment]
> add `show: true` as a sub of `action_button` `compact: true action_button: mode: custom show: true` If you use the Visual Editor when adding the card all the default settings will be set and you will not have this issue. Use my solution above otherwise.

It works! 
Thank you
