### ISSUE TITLE
Cover slider disappearing

### ISSUE THREAD

**Issue by KairuByte** [mattieha/slider-button-card#20]
Not sure if this is a bug, or intentional. But when I use a cover slider, it shows for a short while until the card just blanks out again. Is it possible to keep the slider state showing?

Intent behind this is easier state views of things like garage doors and blinds.

This may only be happening for binary options, as I do not have any covers that allow for partial closure.

**Comment by mattieha** [comment]
This is indeed a bug, I'm refactoring the code at the moment, so there is no need anymore to do calculations on resize.
