### ISSUE TITLE
Allow the use of groups

### ISSUE THREAD

**Issue by jonathanathe** [mattieha/slider-button-card#21]
**Is your feature request related to a problem? Please describe.**
First of all congratulate you for this I think it is very useful and I plan to use it a lot the question is that I found something important that I should have for the type of functionality that gives for example the control of lights.

First and foremost in my case is the possibility that there should be able to use groups in my case in the ceiling I have 4 bulbs and do not care much to have to control individually but as a group, I think it is a major flaw that you can not perform this control.

**Describe the solution you'd like**
Integration of groups within the interface to be able to control several and not just one.

**Comment by mattieha** [comment]
Thank you for your feedback.
I'll look into adding support for groups.

In my setup I use [Light Groups](https://www.home-assistant.io/integrations/light.group/) to control multiple lights at once.
This is supported by the card since the `light.group` entity has the domain `light`.
