### ISSUE TITLE
Handle unavailable entities

### ISSUE THREAD

**Issue by KairuByte** [mattieha/slider-button-card#38]
Unavailable entities are a little confusing at the moment. If you don't have state showing they appear identical to available entities.

I think the best visual indicator would be to have the entire card greyed out? Perhaps an "unavailable" icon option, and/or grey out the icons.

**Comment by mattieha** [comment]
I guess on mobile is not clear enough, on desktop the cursor changes on hover.

**Comment by mattieha** [comment]
Improvement for unavailable enttity:

![image](https://user-images.githubusercontent.com/3931195/122595145-4b186c00-d068-11eb-91c6-2a339d660d6e.png)
