### ISSUE TITLE
color temp not used as state color for background

### ISSUE THREAD

**Issue by poudenes** [mattieha/slider-button-card#39]
Slider Addon version: 1.2.0
Chrome OSX: 91.0.4472.106
Safari: 13.1.2 (13609.3.5.1.5)

Safari is not working at all (there is a issue report)

In chrome the button is working, but when you select a color then the background is used the same color. When you switch to color temperature there is nothing changes.. It still keep the color selected

**Comment by mattieha** [comment]
Fixed in v1.6.0
