### ISSUE TITLE
Text appering on slider.

### ISSUE THREAD

**Issue by habiben** [mattieha/slider-button-card#41]
**Thanks for a beautiful card!**
I have found this little bug appearing suddenly.
When moving the slider the text"MOVE" appears. After slideing the text "PRE MOVE 2" appears.
see attached image.

Chrome Version 91.0.4472.77
Mac OS Catalina 10.15.7

Cheers

<img width="523" alt="Skärmavbild 2021-06-17 kl  22 06 24" src="https://user-images.githubusercontent.com/36888090/122465718-b9055a80-cfb8-11eb-901d-49cd994efba3.png">

**Comment by mattieha** [comment]
Are you using v1.3.2-beta? This was a test for ios...

**Comment by mattieha** [comment]
There is a new release v1.4.0 now, please install this one.
