### ISSUE TITLE
my fan can't slide to full speed

### ISSUE THREAD

**Issue by haigaru** [mattieha/slider-button-card#42]
My fan has 3 speeds, I can only slide number 1 and 2 (33% and 66%)

**Comment by mattieha** [comment]
Can you please provice:
- OS + version
- Card version

**Comment by haigaru** [comment]
OS + version: Hassio (supervisor-2021.06.3 and core-2021.6.5)
Card version: 1.4.0
thank for reply :)

**Comment by mattieha** [comment]
Forgot to ask which browser you are using?

**Comment by haigaru** [comment]
google chrome and win 7 64bit

**Comment by haigaru** [comment]
i use google chrome browser

**Comment by pickeld** [comment]
Same here . Unable to reach 100%

**Comment by mattieha** [comment]
@haigaru @pickeld Can u provide me the attributes of your fan entity please?
For example:
```
speed_list: off, low, medium, high
preset_modes: 
speed: high
percentage: 100
percentage_step: 1
preset_mode: null
friendly_name: Living fan
supported_features: 1
```

**Comment by pickeld** [comment]
speed_list:
  - low
  - medium
  - high
preset_modes: []
speed: low
percentage: 33
percentage_step: 33.333333333333336
preset_mode: null
friendly_name: Balcony Fan
supported_features: 1

**Comment by haigaru** [comment]
My config same @pickeld 

speed_list:
  - low
  - medium
  - high
preset_modes: []
speed: low
percentage: 33
percentage_step: 33.333333333333336
preset_mode: null
friendly_name: workroom kenko Fan
supported_features: 1

**Comment by haigaru** [comment]
@mattieha many thanks, the card worked perfectly

**Comment by johntdyer** [comment]
Can someone post a complete example of their fan YAML here, its not clear to me how to use it
