### ISSUE TITLE
No support for Firefox

### ISSUE THREAD

**Issue by mattieha** [mattieha/slider-button-card#5]
At this moment there is no support for Firefox

**Comment by ShaneQi** [comment]
First of all, great idea and great work! Works perfectly on Chrome!

Not working for me on Safari nor iOS app. 
Supporting Safari might be a bit of a stretch, but I think iOS app should be supported.
When I have time, I can offer some help if nobody beats me by then.

How it looks on iOS app:

![IMG_93ACEA8EE16B-1](https://user-images.githubusercontent.com/7324708/121734984-1ed67b80-cabb-11eb-924b-b4a8b05d3843.jpeg)

**Comment by mattieha** [comment]
Thanks for your feedback, I totally agree with you about the support for iOS. Since I don't own an iPhone I haven't had the chance to check it, safari is webkit so I hoped it would just work.

The problem is I use pseudo elements :before and :after on the range input. Apparently this is only supported in Chrome.
I guess the best way forward is to refractor the whole thing and don't use an input range at all.

I'll make this highest prio on the todo list 👍
