### ISSUE TITLE
Light vs. Switch - toggle_on_click

### ISSUE THREAD

**Issue by adulovic** [mattieha/slider-button-card#50]
**Checklist:**

- [X] I updated to the latest version available
- [X] I cleared the cache of my browser

**Release with the issue:**
1.40

**Last working release (if known):**

**Browser and Operating System:**
Chrome and Windows 10

**Description of problem:**
  Switches work great, as do fans and smart lightbulbs. I do however have a slight problem with simple on/off lights mapped from switches.
  As you probably know, in Home Assistant you can define switches which you want to be treated as lights (which is great for all my smart switches controlling actual lights).
With your awesome card, I can easily use something like 'switch.office_lamp' in the card to control the switch and thereby the light, but I would prefer to use 'light.office_lamp' instead. 
  I tried setting the 'toggle_on_click' flag, and it does work as expected to switch the light on, but not to switch it off. The only way it switches off is using the 'action button'.
  All in all, it is a fantastic custom card, and I want to use it for all my buttons, but it also shows some strange and unpredictable behavior which I'm sure you will like to look into. Here are some examples:
1) The light is on - and shown as on by the action button, but shown as off by the card color, icon color, and state caption. 
2) Sometimes you need to click twice to get the card to change background color. First click changes the action button state (and switches on the light), then the second click changes the card itself (to show that the light is on).
3) Light is on, card is colored, all looks good. A few minutes later, the card, icon and state all revert to display 'off', while the action button and actual light are 'on'.

**Javascript errors shown in the web inspector (if applicable):**

```

```

**Additional information:**
If needed, I can try and come up with a more detailed list and some images to help you debug.

**Comment by mattieha** [comment]
@adulovic Thanks for your feedback!
I didn't realize switches mapped to light only supported on/off, should have tested that as I use these myself.
Fix is almost ready.

The three examples you provided, are they all related to this specific issue (switch mapped to light)?

**Comment by adulovic** [comment]
Yes, all three examples are related to the same light vs switch issue. You might also want to look at the behavior of light groups vs. regular groups. (ex. light.upstairs_lights vs. group.upstairs_lights).

On an unrelated subject, the color schemes can sometimes look less than fantastic depending on the theme used. 
The themes I use change for daytime / night, and while trying out various themes, I noticed that I sometimes end up with a teal icon on a teal background, or a light grey text on a slightly darker grey background, both of which are almost impossible to see. 
Perhaps using a transparent background and the built in CSS variables could provide more consistent styling within any given theme. (ex. var(--error-color) instead red,  var(--primary-color) instead of teal, etc. ).

**Comment by nepozs** [comment]
I have the same issue - Philips Hue integration exposes smartplug as light, (but of course with on/off capability only, but it is impossible to change device_class from light to switch in manner like defining switch as light), so I also can test future fix.

**Comment by mattieha** [comment]
Should be fixed now in v1.6.0

**Comment by nepozs** [comment]
For me it works as expected.
