### ISSUE TITLE
add support for climate entities

### ISSUE THREAD

**Issue by Mearman** [mattieha/slider-button-card#53]
I'm really liking the style of this component far more than a lot of similar ones.

I'm wondering if you could add support for climate elements with a min and max value. For example I could have my wall-mounted dashboard have a min and max control of 14-21C

**Comment by mattieha** [comment]
Added to the roadmap, will definitely implement this.

**Comment by mattieha** [comment]
@Mearman I've made a beta release `v.1.7.0-beta` with support for climate entities, could you please test this?

**Comment by dougiteixeira** [comment]
> @Mearman @dougiteixeira I've made a beta release `v.1.7.0-beta` with support for climate entities, could you please test this?

For me it works well.

**Comment by Mearman** [comment]
Works a treat!
Were you able to add a field for setting a min and max range?
Also is it currently possible to set a custom colour gradient? e.g. blue at 15C to red at 25C

**Comment by mattieha** [comment]
Added in v1.9.0

@Mearman 

1. Mode is show now, support for current temp will be added in feature for templating.
2. min and max are auto filled from `min_temp` and `max_temp` on the entity
  a. Can be manually overridden by setting `slider.min` and `slider.max` options in yaml
3. Not currently possible, I like the idea though
