### ISSUE TITLE
State icons are not respecting customization of device classes AND opposite state colors

### ISSUE THREAD

**Issue by olympia** [mattieha/slider-button-card#55]
**Checklist:**

- [x] I updated to the latest version available
- [x] I cleared the cache of my browser

**Release with the issue:1.5.1

**Last working release (if known):**

**Browser and Operating System: Version 91.0.4472.114 (Official Build) (64-bit) / W10

**Description of problem: I had to re-classify my Velux shutters as shutters in customize.yaml because they were classified as windows by defaults. Slider-button-card doesn't respect the re-classification and continue to display the window icon and the states of the window icons for open/close status. 

The below screenshot shows the difference between default HS entity card with correct state icons and the slider-button-card with incorrect state icons.

It also look like that the state color is the opposite compared to the HA default, or am I miss something here?

![image](https://user-images.githubusercontent.com/1816315/122801920-03dae700-d2c5-11eb-8286-d9eefe997799.png)

**Javascript errors shown in the web inspector (if applicable):**

```

```

**Additional information:**

**Comment by mattieha** [comment]
This is now fixed in v1.5.2
Supported device classes for cover:
- `blind`
- `door`
- `garage`
- `shutter`
- `window`

Fallback to `window` for other device classes.

For opposite state colors make sure `icon.use_state_color` is set to `true`.

**Comment by olympia** [comment]
This is great! Thank you! 
State icon works perfectly now according to the device class!

However, color of the state icon is still the opposite (I was already using `icon.use_state_color` set to `true`).
I open a separate issue for this.
