### ISSUE TITLE
Add possibility to change light color temperature

### ISSUE THREAD

**Issue by mjaschreuder** [mattieha/slider-button-card#57]
Awesome job! Really like this card.

Maybe a feature for the future: the possibility to select the value the slider is affecting. In my case for example: change the color temperature from my ceiling lights. Not sure if it's possible but it would make the card even more useful.

I'm not a professional programmer, but let me know if there is anything I can do.
Thanks again.

**Comment by mattieha** [comment]
Thanks, this feature was already half implemented.
In the next release this will be configurable.

**Comment by mattieha** [comment]
Released in v1.6.0 see [readme](https://github.com/mattieha/slider-button-card#attributes) for config, for now you have to set this manually via yaml. Visual editor option follows in next release.

**Comment by mjaschreuder** [comment]
Thank you! It works like a charm.
