### ISSUE TITLE
Possible to add support for slider dimmer groups?

### ISSUE THREAD

**Issue by Obelixje** [mattieha/slider-button-card#58]

**Comment by Obelixje** [comment]
I am using slider-button-card now for a few days. 
I really like this card.

I would like to have the solution to also use the slider to dim a  group of lights.

**Comment by mouth4war** [comment]
Just use light groups in ha.

**Comment by mattieha** [comment]
Just like mouth4war said use Light groups, see this [comment ](https://github.com/mattieha/slider-button-card/issues/21#issuecomment-861874908)

**Comment by Obelixje** [comment]
I missed this closed comment.
I have changed my groups last night according to mouth4war, and slider on groups does work now.

Great custom card this is!!
Thankyou
