### ISSUE TITLE
Improve mobile touch

### ISSUE THREAD

**Issue by mattieha** [mattieha/slider-button-card#6]
With `slider.direction` set to `top-bottom` or `bottom-top` scrolling is also triggered and sliding is difficult / impossible.

**Comment by matejdro** [comment]
An idea for mobile: From what I see (can't test yet, I'm on Firefox), card works by sticking the sliding position to the current cursor position. This works fine on desktop where you can position your mouse precisely, but it is harder on mobile.

What if it behaved more like a touchpad where user can just drag a finger left or right and value would decrease/increase, without sticking to the finger position?

**Comment by d-edge82** [comment]
+1 for this

Thanks for all the hard work, but unfortunately this is useless for me if does not support mobile\tablet usage

Thank you!
