### ISSUE TITLE
Another Cover (Awning device to be exact) reverse problem.

### ISSUE THREAD

**Issue by TheDukeSr** [mattieha/slider-button-card#63]
My Cover is an **Awning device class**.

I've seen previous reported issue's about this problem, but none about a **Awning** device class yet. 
So therefore another report for this class.
[Cover device classes explained](https://www.home-assistant.io/integrations/cover/)

When I set slider to open 20%, the Awning goes to 80% !
Also Icon color, Power button, and Slider state and Percentage are all reversed.
The only thing correct is the Status text Open/Closed.

Hope to see a extra "reverse: true/false" manual option soon.

- [ x] I updated to the latest version available
- [ x] I cleared the cache of my browser

Regards,

The Duke.

**Comment by mattieha** [comment]
@TheDukeSr 
In v.1.7.0 there is a `slider.invert` option, for cover entities it defaults to `true`.
Add `invert: false` in yaml to invert the logic, no visual editor option yet.
Please let me know if this works for you.

**Comment by TheDukeSr** [comment]
> @TheDukeSr
> In v.1.7.0 there is a `slider.invert` option, for cover entities it defaults to `true`.
> Please let me know if this works for you.

Works Perfect ! Thnx.
