### ISSUE TITLE
Slider to switch always set to 100% instead just switch on.

### ISSUE THREAD

**Issue by nepozs** [mattieha/slider-button-card#65]
**Checklist:**

- [x] I updated to the latest version available
- [x] I cleared the cache of my browser

**Release with the issue:**
all I've tested (current v1.5.3 and some older eg. v1.5.2)

**Last working release (if known):**
none

**Browser and Operating System:**

Firefox current 89.0.2 and older 89.0.1, Windows x64, but looks like browser independent (Chrome also tested)

Slider to switch always set lights to 100% instead just switch on.
I'm using some lights stronger then it is needed for normal everyday use (but eg. full power useable when I change my desk in a lab :P), so they are normally switched on with brightess 60% or 72%, but when using "slider to switch" mode, it always sets brighness to 100%.

Action button works properly - it acts as toggle, but "slider to switch" also should work as toggle.

**Comment by mattieha** [comment]
Good point, indeed it toggles to max now. I'll fix this in next release.

**Comment by mattieha** [comment]
Fixed in v1.6.0

**Comment by nepozs** [comment]
Thanks, it works flawless.
