### ISSUE TITLE
Invert percentage (as an option)

### ISSUE THREAD

**Issue by barmazu** [mattieha/slider-button-card#73]
Hi,

Thank you for this great UI extension.
However I have covers that are providing reversed percentage for state (100% means cover is (fully) closed, 0% means (fully) open).
So currently all my covers are basically "inverted" on your buttons (-:
Is it possible to add "invert_percentage", "invert_open_close" or similar sounding option in the foreseeable future?

Thank you for your considerations on this one.

**Comment by TheDukeSr** [comment]
Sounds like the same problem???
Please check out: [Issue #63 ](https://github.com/mattieha/slider-button-card/issues/63)

**Comment by mattieha** [comment]
@barmazu 
In v.1.7.0 there is a `slider.invert` option, for cover entities it defaults to `true`.
Add `invert: false` in yaml to invert the logic, no visual editor option yet.
Please let me know if this works for you.

**Comment by red-machine95** [comment]
> 
> 
> @barmazu
> In v.1.7.0 there is a `slider.invert` option, for cover entities it defaults to `true`.
> Add `invert: false` in yaml to invert the logic, no visual editor option yet.
> Please let me know if this works for you.

Finally! It's working.
Thanks

**Comment by barmazu** [comment]
Amazing @mattieha!
It worked out perfectly.
Thank you!!!

**Comment by barmazu** [comment]
OK, one minor thing I noticed @mattieha
The state I'm seeing is not reversed. Shouldn't this be reversed too?
Ie `return this.invert ? closedLabel : openLabel;` -> `return this.invert ? openLabel : closedLabel;`
At 100% I should see "closed" state... And now I'm seeing "open"
Nonetheless.

Thanks. Amazing work.
