### ISSUE TITLE
Climate not supported?

### ISSUE THREAD

**Issue by Reynders1** [mattieha/slider-button-card#76]
Hi,

I just installed the lashes version (1.9.0), clear the browser (Safari) cache and restarted HA.
Unfortunately I can't use any climate entity! See below.

Any idea why?

<img width="484" alt="Screenshot 2021-06-30 at 12 50 11" src="https://user-images.githubusercontent.com/44923513/123948990-5477d180-d9a2-11eb-9c70-426046db4bc0.png">

**Comment by Mearman** [comment]
Seems fine for me on 1.9.0. 
Have you tried restarting and refreshing your UI?
![image](https://user-images.githubusercontent.com/1331872/123965107-0798f880-d9ac-11eb-901f-4df52c698322.png)

**Comment by Reynders1** [comment]
Yes, did it twice. And just now a third time and ... it work!

Sorry for the trouble!
