### ISSUE TITLE
Compact mode breaks layout when used with custom action button

### ISSUE THREAD

**Issue by cicero200272** [mattieha/slider-button-card#81]
![slider](https://user-images.githubusercontent.com/15817602/124021931-71d18d80-d9ec-11eb-950d-035533a82fa2.png)

**Comment by mattieha** [comment]
@cicero200272  Thanks for your feedback, could you provide some more information: the config you are using and your platform/browser?

This is what looks like for me in windows/chrome:
![image](https://user-images.githubusercontent.com/3931195/124331912-864e8b00-db90-11eb-88cd-8f22da39e333.png)

**Comment by cicero200272** [comment]
Hi @mattieha, 

it seems that `show: true` is mandatory for the action_button. The layout gets broken as shown in the screenshot above when it's not included in the config.

I recognized that the same applies to the slider, if I omit the `direction` parameter, the slider does not work properly any more. Aren't the default values supposed to kick in in this case?

Anyway, now the card is working fine and I close this bug.

Cheers,
Tim
