### ISSUE TITLE
Gradient on iOS (iPad) start with red.

### ISSUE THREAD

**Issue by JShoota** [mattieha/slider-button-card#87]
**Checklist:**

- [X ] I updated to the latest version available
- [ ] I cleared the cache of my browser

**Release with the issue:**
1.10
**Last working release (if known):**
1.10
**Browser and Operating System:**
Official iOS App. iOS 14.3

**Description of problem:**
If I enable gradients for the slider, they show up going from Red at 0% to blue or the entity color, based upon seettings. Screenshot with an example is attached. 
<img width="571" alt="ipad screenshot" src="https://user-images.githubusercontent.com/35128476/124398137-578bfe00-dcd1-11eb-89e7-e9f0fcf55bb7.png">

**Javascript errors shown in the web inspector (if applicable):**

```

```

**Additional information:**
The same dashboard works perfectly in Chrome or the Android app, so the issue seems to be related to iOS.

**Comment by mattieha** [comment]
@JShoota This is fixed now in v.1.10.1 , thanks for your feedback.

**Comment by JShoota** [comment]
Thanks for the quick fix. Love the card!
