### ISSUE TITLE
Group support. 

### ISSUE THREAD

**Issue by larsoss** [mattieha/slider-button-card#91]
very simple actually, I now have a number of Hue lamps in a group for my living room, and it would be great if I could also control them with the slider... then I can make a nice slider dashboard.

**Comment by rhwilr** [comment]
You can use light groups: https://www.home-assistant.io/integrations/light.group/

**Comment by mattieha** [comment]
Since a lot people create issues for group support I've added a section to readme for it:
https://github.com/mattieha/slider-button-card#groups
