### ISSUE TITLE
Multiple action buttons (HVAC mode selection in climate slider)

### ISSUE THREAD

**Issue by mouth4war** [mattieha/slider-button-card#92]
**Is your feature request related to a problem? Please describe.**
To change HVAC mode, multiple steps are needed because the slider doesnt have buttons for each mode.

**Describe the solution you'd like**
Ability to add multiple buttons to slider.

**Comment by mattieha** [comment]
This is similar to #16 , it's added to the roadmap, will definitely look into this!
